version: '3.3'
services:
  web:
    build: ./build
    image: helloworld
    ports:
      - '3000:3000'
  tester:
    image: codeception/codeceptjs
    volumes:
      - ./tests:/tests
    depends_on:
      - web
      - chrome
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444'
      - '5900'

