version: '3.3'
services:
  web:
    container_name: web
    build: ./build
    image: helloworld
    ports:
      - '9090:9090'
  tester:
    image: codeception/codeceptjs
    volumes:
      - ./tests:/tests
    depends_on:
      - web
      - chrome
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome
    ports:
      - '4444'
      - '5900'

